### ISSUE TITLE
Error when using Python version 2 instead of Python3

### ISSUE THREAD

**Issue by jeff-luszcz** [wadetb/eliza#2]
Configuration:
MacOS using default Python version (2.7.10) you will get the following error when using the program

```
$ python eliza.py 
How do you do.  Please tell me your problem.
> Hello
Traceback (most recent call last):
  File "eliza.py", line 232, in <module>
    main()
  File "eliza.py", line 228, in main
    eliza.run()
  File "eliza.py", line 214, in run
    sent = input('> ')
  File "<string>", line 1, in <module>
NameError: name 'Hello' is not defined
```

If you use python3 from the command line the program will work as expected.

I'm not sure if you can make it work under Python2. Either way, a note in the readme file could be helpful for people getting started with your script.

Thanks!

**Comment by wadetb** [comment]
Thanks for the report, looks like `input` meant something else in Python 2. I've pushed a fix, and added the usage readme as you suggested.
